name: our_pomodoro
description: "A beautiful Pomodoro Timer app built with Flutter following Clean Architecture principles."
publish_to: 'none'
version: 0.3.1+4

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core dependencies
  get_it: ^8.2.0
  equatable: ^2.0.7

  # State management
  flutter_bloc: ^9.1.1

  # Local storage
  shared_preferences: ^2.5.3

  # Networking (for future features)
  dio: ^5.9.0
  connectivity_plus: ^6.1.5

  # UI
  flutter_svg: ^2.2.1
  lottie: ^3.3.1

  # Utils
  flutter_local_notifications: ^19.4.1
  audioplayers: ^6.5.1
  uuid: ^4.5.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
